# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "sample-lambda-us-east-2-sandbox-000-tfstate"
    dynamodb_table = "sample_lambda-us-east-2-sandbox-000-tflocks"
    encrypt        = true
    key            = "terraform.tfstate"
    profile        = "default"
    region         = "us-east-2"
  }
}
