# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  profile = "default"
  region  = "us-east-2"
}

provider "aws" {
  alias   = "global"
  profile = "default"
  region  = "us-east-1"
}
